---
title: "Imposed form in the Early Acheulean? Evidence from Gona, Afar, Ethiopia"
author:
- Dietrich Stout^[Department of Anthropology, Emory University, Atlanta, GA, USA;  dwstout@emory.edu]
- Cheng Liu^[Department of Anthropology, Emory University, Atlanta, GA, USA; raylc1996@outlook.com]
- Antoine Muller^[Institute of Archaeology, Mount Scopus, The Hebrew University of Jerusalem, Jerusalem, Israel; antoine.muller@mail.huji.ac.il]
- Michael J. Rogers^[Department of Anthropology, Southern Connecticut State University, New Haven, CT, USA; rogersm1@southernct.edu]
- Sileshi Semaw^[Centro Nacional de Investigación sobre la Evolución Humana (CENIEH), Burgos, Spain; sileshi.semaw@cenieh.es]
abstract: 
|
  ```{=latex}
  TBD.

  \textbf{Keywords:} Gona; TBD; TBD; TBD; TBD; TBD; TBD
  ```
date: "`r Sys.Date()`"
fontsize: 11pt
output: bookdown::pdf_document2
header-includes:
   - \usepackage{textcomp}
   - \usepackage{utopia}
   - \usepackage{lineno}
   - \linenumbers
   - \usepackage{float}
   - \floatplacement{figure}{H}
   - \usepackage{caption}
   - \captionsetup[figure]{font=scriptsize}
   - \captionsetup[table]{font=scriptsize}
linestretch: 1.5
link-citations: yes
linkcolor: blue
bibliography: bibliography.bib
csl: apa.csl
editor_options: 
  markdown: 
    wrap: sentence
---

# Introduction

The imposition of intended form on artifacts has long been viewed as a watershed in human cognitive and cultural evolution and is most commonly associated with the emergence of "Large Cutting Tools" (LCTs) in the Early Acheulean [@isaac1976; @kuhnEvolutionPaleolithicTechnologies2020; @holloway1969].
However, this interpretation of Acheulean LCTs as intentionally designed artifacts remains controversial.
Alternative proposals range from the possibility that LCTs were unintended by-products of flake production [@moore2016; @noble1996] to the suggestion that their form was "at least partly under genetic control" [@corbey2016].
Even accepting that LCT form was to some extent intended, there is substantial disagreement over the specificity of design.
Some analyses have indicated that shape variation in Acheulean handaxes is largely a result of resharpening [@iovita2011; @mcpherron2000] whereas others find form to be unrelated to reduction intensity and more likely to reflect normative expectations of what handaxes should look like [@garcía-medrano2019; @shiptonHandaxeReductionIts2015a; @shipton2020].
Such debates about shape of Acheulean LCTs may appear narrowly technical but have broad relevance for evolutionary questions including the origins of human culture [@corbey2016; @tennie2017; @shiptonHandaxeReductionIts2015a], language [@stout2012], teaching [@gärdenfors2017], brain structure [@hecht2015], and cognition [@stout2015; @wynn2016].
To examine these questions, we studied the complete collection of Early Acheulean flaked pieces from 5 sites at Gona Project Area and compared them with Oldowan cores form 2 published sites at Gona.
By comparing shape variation to measures of flaking intensity and patterning, we sought to identify technological patterns that might reveal intent.

## Identifying design

There is a broad consensus that refined handaxes and cleavers from the later Acheulean resulted from procedurally elaborate, skill intensive, and socially learned production strategies [@caruana2020; @garcía-medrano2019; @moore2020; @sharon2009; @shiptonEvolutionSocialTransmission2019; @stout2014] although debate over the presence of explicit, culturally transmitted shape preferences continues [@iovita2011; @moore2020; @shipton2020; @wynn2018].
There is much less agreement regarding the less heavily worked and formally standardized LCTs typical of the earliest Acheulean [@beyene2013; @delatorre2018; @diez-martín2015; @lepre2011; @semaw2018].
Such forms continue to occur with variable frequency in later time periods [@mcnabb2015], and may be especially prevalent in eastern Asia [@li2021].
Although formal types have been recognized in the Early Acheulean and are commonly used to describe assemblages, many workers now see a continuum of morphological variation [@duke2021; @kuhn2020; @presnyakova2018]including the possibility that simple flake production remained an important [@shea2010] or even primary [@moore2016] purpose of Early Acheulean large core reduction.

Typologically, LCTs are differentiated from Mode 1 pebble cores on the basis of size (\>10cm) and shape (elongation and flattening) [e.g., @isaac1977].
This consistent production of large, flat, and elongated cores in the Achuelean has long been thought to reflect the pursuit of desired functional and ergonomic properties for hand-held cutting tools [@wynn2018].
Unplanned flaking can sometimes produce cores that fall into the LCT shape range [@moore2016] and this is one possible explanation of the relatively small "protobifaces" that occur in low frequencies in Oldowan assemblages [@isaac1997].
However, the Early Acheulean is clearly distinguished from the Oldowan by the production of larger artifacts necessitating the procurement and exploitation of larger raw material clasts.
Although studies of handaxe variation often focus on shape rather than size, this shift is an important aspect of artifact design with relevance to both production and function.

Production of larger tools was accomplished either through a novel process of detaching and working Large Flake Blanks (LFBs) from boulder cores or simply by using larger cobble and slab cores [@delatorre2018; @isaac1969; @semaw2018].
Both may involve similar flaking "strategies" (e.g., bifacial or multifacial exploitation) to those present in the Oldowan [@duke2021] but require more forceful percussion to detach larger flakes.
This increases the perceptual motor difficulty of the task [@stout2002] and in many cases may have been accomplished using different percussive techniques and supports [@semaw2009].
These new challenges would have increased raw material procurement [@shea2010] and learning costs [@pargeter2019] as well as the risk of serious injury [@gala2023] associated with tool production.
This strongly implies intentional pursuit of offsetting functional benefits related to size increase.
These likely included tool ergonomics and performance [@key2017] as well as flake generation, resharpening, and reuse potential [@shea2010].
Early Acheulean LCT production is thus widely seen as a part of shifting hominin behavioral ecological strategies including novel resources and mobility patterns [@linaresmatás2021; @rogers1994].

The degree of intentional design reflected in the shape of Early Acheulean LCTs is more difficult to determine.
For example, LFB production using a simple "least effort" bifacial/discoidal strategy will tend to generate predominantly elongated (side or end struck) flakes [@toth1982] whether or not this is an intentional design target.
Similarly, the difficulty of flaking relatively spherical cobbles [@toth1982] might bias initial clast selection and subsequent reduction toward flat and elongated shapes even in the absence of explicit design targets.
On the other hand, it has been argued that the shape of Early Acheulean LFBs was intentionally predetermined using core preparation techniques [@delatorre2018] and many researchers perceive efforts at intentional shaping in the organization of flake scars on Early Acheulean handaxes and picks [@beyene2013; @delatorre2018; @diez-martín2015; @duke2021; @lepre2011; @semaw2009].
To date, however, the identification of Early Acheulean shaping has generally relied on qualitative assessment by lithic analysts.
Such assessment may in fact be reliable, but is subject to concerns about potential selectivity, bias, and/or overinterpretation [@davidson2002; @moore2016].
Notably, a 3-dimensional morphometric (3DGM) study by Presnyakova, et al. [-@presnyakova2018] concluded that LCT shape variation in the Okote Member (\~1.4 mya) at Koobi Fora was largely driven by reduction intensity rather than different knapping strategies.
However, this study did not directly address the presence/absence of design targets constraining the observed range of variation.

In later Acheulean contexts, reduction intensity effects are commonly equated with resharpening and seen as an alternative to intentional form imposition [@mcpherron2000].
Across heavily-worked and relatively standardized LCT assemblages [e.g. @shipton2020], a *lack* of association between morphology and reduction intensity has be used as an argument-by-elimination for the presence of imposed morphological norms or \"mental templates\" [@garcía-medrano2019; @shipton2015; @shipton2023].
However, in the less heavily-worked and more heterogenous assemblages typical of the early Acheulean [@kuhn2020], it is equally plausible that increasing reduction intensity would reflect degree of primary reduction rather than subsequent resharpening [@archer2010].
In this case, reduction intensity effects on morphology would have the opposite interpretation:  more reduction should result in closer approximation of a desired form if such were present.
For example, Beyene, et al. [-@beyene2013] found that increasing flake scar counts were associated with increasing handaxe refinement through time at Konso, Ethiopia, which may reflect a more general trend in the African Acheulean [@shipton2018].

Interpretive approaches address this quandary by \"reading\" the organization of scars on individual pieces to infer intent, but an adequate method to objectively quantify these insights has yet to be developed.
Current measures of reduction intensity, such as the scar density index (SDI) [@clarkson2013], are designed to estimate total mass removed from a core and are reasonably effective [@lombao2023].
However, mass removal was not the objective of Paleolithic flaking.
Indeed, knapping efficiency is usually conceived as generating an outcome while *minimizing* required mass removal.
This is true whether the desired outcome is a useful flake, a rejuvenated edge, or a particular core morphology.
In simple flake production, mass removed is probably a good reflection of the completeness of exploitation (\"exhaustion\") of cores and may have implications for required skill [@toth1982; @pargeter2023] as well as raw material economy [@reeves2021; @shick1987].
However, in core shaping and resharpening, mass removal would typically represent an energetic and raw material cost to be minimized, and might even interfere with function [@keyHandaxeShapeVariation2019].
Without further information, relationships between artifact shape and reduction intensity are thus open to conflicting interpretations as evidence of intentional design or its absence.

Li, et al. [-@li2015] proposed a Flaked Area Index (FAI) as an alternative to SDI as a measure of reduction intensity, arguing that its validity is supported by an observed correlation (r=0.424) with SDI.
However, they also explain that \"flaked area does not necessarily relate to the number of flake scars\...a small number of large scars can produce a large area of scar coverage, and conversely, a large number of small scars can produce a small area of scar coverage.\" (p. 6).
We suggest that what FAI actually captures is the spatial extent modifications to the surface of a core.
It is thus complementary to the measure of volume reduction provided by SDI and provides additional information to inform technological interpretations.
For example, a correlation between FAI and artifact form without any effect of SDI would suggest a focus on \"least-effort\" shape imposition whereas the opposite pattern would be consistent with relatively intense resharpening of spatially restricted areas on the core.
A lack of shape correlation with either measure would be expected for simple debitage with no morphological targets whereas a strong correlation with both would indicate a highly \"designed\" form achieved through extensive morphological and volumetric transformation.
In the current study we thus considered SDI and FAI together in order to evaluate evidence of intentional shaping in the early Acheulean of Gona.

## Measuring artifact form and modification

Hypotheses: 1) Valid technological types should produce clear morphological clusters with different reduction trajectories vs. points along a continuum.
2) Debitage is indicated by relation of SDI and flaked area to core size but not shape.
3) Shaping is indicated by relation of flaked area to shape & weaker or absent relations of shape with SDI.
Shape independent of size.
4) Shaping plus resharpening means shape should be related to core size and SDI (Shipton)

It is even controversial whether asia is "acheulean" Prevailing opinion, but Beyene.
A conservative interpretation of available evidence is that LCT production was guided by a recurring set of functional, ergonomic, and aesthetic design preferences [@wynn2018] with other elements free to vary in response to raw materials, use life, and random population dynamics like drift, bottlenecks, and founder effects [@kuhnEvolutionPaleolithicTechnologies2020; @lycett2016].

# Materials and Methods

## Materials

Archaeological Sample

## Methods

### Artifact Shape Measurement

Three-dimensional scanning and geometric morphometric (3DGM) methods are becoming increasingly common in the study of LCT form [@archer2010; @caruana2020; @li2021; @lycett2006; @presnyakova2018; @shiptonHandaxeReductionIts2015a].
These methods can provide high-resolution, coordinate-based descriptions of artifact form including detailed information about whole object geometric relations that is not captured by conventional linear measures [@shott2010].
However, they also impose additional costs in terms of data collection and processing time as well as required equipment, software, and training.
Insofar as these costs might present an obstacle to participation by some researchers and/or draw resources away from other activities, they must be balanced against benefits.
In particular, it is not clear that these powerful methods are required in order to describe relevant variation in Acheulean LCT shape.
Unlike hominin crania or even projectile points, Acheulean handaxes, cleavers, and picks are not complex shapes.
Individual LCTs exhibit complex morphologies defined by idiosyncratic scar patterns, but these details are largely noise at the level of comparative analyses.
Laser-scanning 3DGM studies of LCTs collect vast amounts of shape data, but typically discard upward of 50% of the observed variation in order to focus on two or three interpretable principal components.
Across studies, these PCs consistently corresponding to basic features like elongation, relative thickness, pointedness, and position of maximum thickness that also emerge from lower-resolution spatial data [@archer2010; @garcía-medrano2019; @lycett2006] and studies employing linear measures rather than spatial coordinates [@crompton1993; @pargeter2019].
Thus, while the level of detail enabled by 3DGM is arguably useful for building artifact phylogenies [@okumura2019], it is of questionable behavioral/technological relevance for the study of LCTs.
For these reasons, we favored the use of simple caliper-based linear measures to quantify shape in our study.
Nevertheless, Shott and Trail [-@shott2010] do identify three potential shortcomings of linear measurements compared to 3DGM.
We considered each in the context of our particular materials and research questions.
First, conventional linear measures capture the direction (e.g. length \> breadth) but not the location of geometric relations (e.g. position of maximum breadth).
We address this by collecting linear measures defined by homologous semi-landmarks.
All artifacts were oriented along their maximum dimension, which was measured and defined as "length." The next largest dimension orthogonal to length was used to define the plane of "breadth," with the dimension orthogonal to this plane defined as "thickness." Breath and thickness measures were then collected at 25%, 50%, and 75% of length, oriented so that 25% Breadth \> 75% Breath.
To partition variation in shape from variation in size, we divided all linear measures by the geometric mean [@lycett2006].

Second, linear measures risk reducing complex forms to overly simplistic "stick figure caricatures" [@shott2010].
However, whether or not this risk actually presents a problem depends on the particular artifacts and research questions involved.
We have already noted that 3DGM LCT studies typically evaluate only a small portion of the measured variation.
To better evaluate the measurement density required for our study, we reanalyzed a data set of 128 experimental handaxes previously published by Pargeter et al. [-@pargeter2019].
These data comprise 19 linear measures (length plus breadth and thickness at 10% increments of length) collected from digital photos using the same orientation protocol described above.
We conducted a PCA on the full set of 19 measures and again on a reduced set of 7 (length plus breadth and thickness at 30%, 50%, and 70% length).
Despite this reduction, the first two components from each analysis displayed strikingly similar component loading matrices (PC1 positive on length and tip breadth, negative on thickness; PC2 positive on base breadth, negative on length and thickness) almost perfectly correlated component scores for individual pieces (PC1 r=0.919, PC2 r=0.913).
As a further check, we performed the same comparison on a subset of the current archaeological sample from Gona for which photos were available for measurement (n = 50).
This produced two PCs that were not only similar with each other, but also matched the PCs extracted from the experimental handaxe sample.
Individual piece component scores were again highly correlated (r=0.975 and 0.927 respectively).
Seven linear measures thus appear sufficient to explain technologically/behaviorally relevant shape variation in our sample.
Third, linear measures may struggle to capture attributes such as cross-sectional area and shape (e.g. Caruana, 2020) more easily assessed using 3DGM.
Particularly relevant here are measures of surface area used to calculate indices of reduction intensity [@shiptonHandaxeReductionIts2015a; @clarkson2013] and surface modification [@li2015] used in our study.
Clarkson [-@clarkson2013] advocates the use of 3D surface area measures as more accurate than estimation from linear measures (e.g. surface area of a rectangular prism defined by artifact dimensions).
However, he also found that the error introduced by the linear approach was a highly systematic, isometric overestimation of surface area and that results correlated with direct 3D measures with an impressive r2 = 0.944 and no effect of variation in core shape.
Insofar as it is variation in the relationship between surface area and flaking intensity that is of interest, rather than the absolute size of artifacts, such consistent overestimation is not problematic.
Here we improved on the prism-based surface area formula (2LW + 2LT + 2 WT) by using our 7 recorded dimensions to more tightly fit three prisms (Figure 1) around the artifact: SA = W1T1 + 2(.33L \* W1) + 2(.33L \* T1) + 2(.33L \* W2) + 2(.33L \* T2) + 2(.33L \* W3) + 2(.33L \* T3) + W3T3.
Surface area calculated in this way correlates with mass2/3 at r2 = 0.947 in our sample.

PCA on GM-transformed caliper measures (length, 3 breadth, 3 thickness).
Length is maximum dimension, piece oriented so that Br1\>Br3

Typological and technological attributions considered unreliable.
Data grouped according to context (\~2.5 mya Oldowan sites vs. \~1.5 mya Acheulean sites) and blank form (cobble, flake, indeterminant).

Associations between form and reduction intensity are considered as an indicator of "imposed form." Such form could reflect mental templates and/or biased flaking patterns due to functional or technological constraints

### Reduction Indices

Research by Clarkson and Shipton has established the Scar Density Index (SDI = number of flake scars \> 1cm per unit surface area) as a reliable indicator of mass removed from a core across technologies [@clarkson2013] and for handaxes specifically [@shiptonFlakeScarDensity2015].
We thus use SDI as an indicator of reduction intensity (mass removed) in our study.
However, reduction intensity does not constitute a full description of core modification.
Mass removal is the aim during flake production and extent of shaping are not necessarily the same thing.
For example, imposition of a desired form

# Results

A PCA (covariance matrix) on our 7 linear measures (scaled by geometric mean) for pieces identified two PCs explaining 80% of variance (56.4% and 23.7%).
Rescaled component matrix shows that PC1 reflects "flatness" (length and breadth vs. thickness).
PC

Two-step cluster analysis identified 3 clusters.

Typologically, these loosely correspond to Mode 1 cores, Large Flake/Knifes, and Picks, with handaxes split between knife vs. pick categories.

PC1 differentiates Mode 1 and Mode 2 pretty well, in that M1 cores tend not to be flat or elongated.
Mode 1 exceptions (i.e. misclassified on shape) are generally still distinguishable as smaller and more heavily reduced than Mode 2 (of Mode 1 included in Cluster 1: mean weight =159.4 vs. 635.6, p \< 0.001; Mean logSDI = .74 vs. .20, p \< 0.001).
(of Mode 1 included in Cluster 3: mean weight =224.1 vs. 398.1, p \< 0.001; Mean logSDI = .67 vs. .39, p = 0.004).
We thus treat Mode 1 as a valid techno-morphological category.
Consistent with the characterization of Mode 1 as focused on debitage rather than shaping, we observe a strong power relationship between reduction intensity (SDI) and core size (r2=0.715, p \< 0.001, b1 = -0.872):

In contrast, and also in keeping with a focus on debitage rather than shaping and resharpening, there is no such relationship with shape PCs for SDI:

Cluster 1 is divided from Cluster 3 by PC2 (pointedness).
Cluster 1 is much more likely to be executed on a flake base (91% flakes) vs. cluster 3 (35% flakes).
Cluster 1 is also significantly less reduced (Mean logSDI = .39 vs. .20, p \< 0.001).
So, cluster 1 basically comprises lightly retouched LFB acheulean, with shapes that remain largely within the range of unmodified flakes (n.s. mean difference).

The effect of reduction on LFB acheulean shape is evident only for flaked area (not SDI) and corresponds to decreases in both PCs (i.e. less elongated but more pointy).
The PC1 effect is relatively weak (r2=0.1, p =0.008, Standardized Beta = -0.215).
The PC2 effect is stronger (r2=0.244, p \< 0.001, Standardized Beta = -0.537).
This is most consistent with flaking placed to shape a point.
A weak power effect of SDI on weight (r2=0.178, p \< 0.001, b1= -.330), as well as low number of scars in general, suggests resharpening is not a major factor.

These trends mean that heavily modified flakes enter into cluster 3 (i.e. look like picks).
Indeed, 40% of identifiable bases for cluster 3 are flakes.
Cluster 3 pieces executed on flakes tend to be less pointed regardless of reduction intensity, which is likely a reflection of starting blank form.
Indeed, Mode 2 Cobble bases show no effect of reduction intensity on shape but do show SDI effect on weight (r2=0.432, p \< 0.001, b1=-0.711).
This appears to reflect the presence of cobble blanks that are already relatively pointed without substantial reduction and raises the possibility that these pieces are produced through debitage on pointed cobbles.
Could they start as LFB cores?
look at maximum flake scar size.
Large cores have few, large scars.

These patterns indicates that there is a common reduction trajectory for Mode 2 forms at Gona, regardless of typology or blank form.
Although some pieces start much closer to the terminal morphology than others (i.e. display low PC2 values without substantial reduction), none undergo substantial reduction without becoming pointed.

This uniform trajectory casts serious doubt on the likelihood that picks are a distinct morpho-functional type, although they may represent "4-dimensional design" sensu Kuhn.
edge angles up to 70 degrees are quite efficient and obtuse trimming of butt may help ergonomics.

No evidence for shaping of cobbles.

Acheulean cobbles are larger and more cylindrical (geologically "rollers").
Shape difference may reflect availability and/or selectivity for flake-able shapes.

Some Achuelean flaked cobbles might hypothetically be heavily reduced remnants of giant cores for LFB production.
Size of scars overlaps with LFBs (right).
However, smaller scars are present and so reduction seems to have continued past potential for LFB production.
Cobbles are generally pretty heavily reduced.

Acheulean flaked flakes seem to have been (mildly) shaped to increase elongation and pointedness.
This might have been an explicit design target, a passive result of preferentially flaking working edges, and or a desire to retain length for some reason.

# References
